### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by FBFezz** [goodguydul/phonebooth#2]
The first issue is that there is no fxmanifest. I did make a pr to add it.

The second issue is that the video is on google drive and we need to request access to view it

**Comment by goodguydul** [comment]
Read the Readme. i've told "How to install" this script.

**Comment by FBFezz** [comment]
Ah yeah sorry, bit sleep deprived but the video issue still persists

**Comment by goodguydul** [comment]
Just check again. i've fix it

**Comment by FBFezz** [comment]
Yep
